version: "3.8"
services:
  frontend:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
  backend:
    build: ./
    container_name: backend_c
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true