version: "3.8"
services:
  frontend:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
  backend:
    build: ./
    container_name: backend_c
    ports:
      - '4000:5000'
    stdin_open: true
    tty: true
  mongodb_service:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    ports: 
      - '27018:27017'